from rouge import Rouge

hypothesis = "And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks. So, once we're on YouTube, we'll simply upload a video as we normally would and add subtitles to it as we go. I then simply choose my YouTube videos after clicking on Select Files. Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. So even YouTube knows that if you add subtitles to video, you're going to get more reach and more views. So I've got this video and I want to add subtitles to it. This is the exact video that we typed out manually within YouTube's studio. And then to download it as an SRT file so we can upload it to YouTube, all we're going to do is click on the Options tab right here. And then I'm just going to select the SRT file that we've just automatically generated using VEED."

reference = "We'll be manually adding the subtitles to the YouTube video, but after I've demonstrated how to do that, I'll show you how to automatically create a subtitle SRT file, allowing you to upload both your subtitles and your YouTube video simultaneously in a matter of clicks. Therefore, once we're on YouTube, we'll just upload a video as we normally would and add subtitles to it as we go. After clicking Select Files, I simply select my YouTube videos. You'll see that once we click Next to move on to the next step for the video elements, we now have this new section at the top with Add subtitles directly beneath it. Because of this, YouTube is aware that adding subtitles to video. You'll have a wider audience and more viewers. So I want to add subtitles to this video I have. This is the exact video that we manually typed in YouTube's production facility. All we have to do is click on the Options tab right here to download it as an SRT file so we can upload it to YouTube. I'll just choose the SRT file that VEED just used to generate it automatically after that."
h2 = "So I've got this video and I want to add subtitles to it. And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks. So once we're on YouTube, to add subtitles to our video while we upload it, we're just going to upload a video as we would normally. Now, there's always been the possibility to add subtitles to a YouTube video, but here YouTube implemented this section directly within the upload process because they know how important subtitles are and how important they're becoming because video content is dominating online. Then once we click Next to go to the next step for the video elements, here you'll notice that at the top, we have this new section, which is Add subtitles right next to it. Now we're taken to the YouTube video upload page and this is where I'm going to select the YouTube video I want to upload to YouTube. So I've got this video and I want to add subtitles to it. So as you can see our video is now being uploaded and here we can fill out all the information for our video as if we would normally. And that is how to upload subtitles to a YouTube video after YouTube's new upload process update. Now to add the subtitles, all we're going to do is click on Add right next to add subtitles."
r2 = "I want to add subtitles to this video that I have, so I've got that. Afterwards, I'm going to show you how to automatically create a subtitle SRT file so you can upload your subtitles along with your YouTube video at the same time, in just a few clicks. Initially, we'll be manually adding our subtitles to the YouTube video. So, once we're on YouTube, we'll simply upload a video as we normally would and add subtitles to it as we go. Although it has always been possible to add subtitles to a YouTube video, this section has now been integrated into the upload process because YouTube understands the value of subtitles and how important they are becoming because video content is dominating online. Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. We've now been directed to the YouTube video upload page, where I will choose the YouTube video I want to upload. So I want to add subtitles to this video I have. As you can see, our video is currently being uploaded, and from here, we can enter all the necessary details for our video just like we normally would. And that's how, following YouTube's recent upload process update, to add subtitles to a video. Now to add the subtitles, all we're going to do is click on Add right next to add subtitles."
h3 = "And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks. So once we're on YouTube, to add subtitles to our video while we upload it, we're just going to upload a video as we would normally. Now, there's always been the possibility to add subtitles to a YouTube video, but here YouTube implemented this section directly within the upload process because they know how important subtitles are and how important they're becoming because video content is dominating online. Now we're taken to the YouTube video upload page and this is where I'm going to select the YouTube video I want to upload to YouTube. Then once we click Next to go to the next step for the video elements, here you'll notice that at the top, we have this new section, which is Add subtitles right next to it. So I've got this video and I want to add subtitles to it. So I've got this video and I want to add subtitles to it. So I've got this video and I want to add subtitles to it. And that is how to upload subtitles to a YouTube video after YouTube's new upload process update. Now to add the subtitles, all we're going to do is click on Add right next to add subtitles."
r3 = "Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. We've now been directed to the YouTube video upload page, where I will choose the YouTube video I want to upload. So I want to add subtitles to this video I have. As you can see, our video is currently being uploaded, and from here, we can enter all the necessary details for our video just like we normally would. And that's how, following YouTube's recent upload process update, to add subtitles to a video. We've now been directed to the YouTube video upload page, where I will choose the YouTube video I want to upload. Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. I want to add subtitles to this video that I have, so I've got that. I want to add subtitles to this video that I have, so I've got that. I want to add subtitles to this video that I have. And that's how, following YouTube's recent upload process update, to add subtitles to a video. All we're going to do is add the subtitles now."
h4 = "Then once we click Next to go to the next step for the video elements, here you'll notice that at the top, we have this new section, which is Add subtitles right next to it.Now, there's always been the possibility to add subtitles to a YouTube video, but here YouTube implemented this section directly within the upload process because they know how important subtitles are and how important they're becoming because video content is dominating online. However, as you notice this takes a lot of time, so here's how to automatically generate a subtitle file for your video.So if I click on this, I then select the language that I want to automatically transcribe and turn into subtitles.And as you can see, this process may take a few seconds to a few minutes, depending on the length of your video to automatically transcribe your videos audio into text and turn that text into subtitles.Now, if you want to change and adjust a few things, for example, in this automatically generated transcript, as you can see here, it says, Alex, instead of Alec, so I'm just gonna quickly correct that, but this is a very common mistake, even on the iPhone, my name is always auto corrected to Alex, but I always recommend just quickly going through and checking your subtitles.And then to download it as an SRT file so we can upload it to YouTube, all we're going to do is click on the Options tab right here.So I'm going to head over back to YouTube and this time I'm just going to delete the subtitles that I manually typed in.Click Open and now as you can see, all of the subtitles with the corrections that I made have been imported into YouTube.If you have any questions about adding subtitles to a YouTube video, I would love to hear them in the comment section down below."
r4 = "Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. Although adding subtitles to a YouTube video has always been an option, YouTube decided to integrate this feature right into the upload process because they recognize the value of subtitles and how important they are growing as video content takes over the internet. Here's how to automatically create a subtitle file for your video because, as you can see, this takes a lot of time. In order to choose the language for automatic transcription and creation of subtitles, I need to click on this. And as you can see, depending on the length of your video, this process may take a few seconds to a few minutes to automatically convert your video's audio into text and create subtitles. Now, if you want to change and adjust a few things, for instance, in this automatically generated transcript, as you can see here, it says Alex, instead of Alec, so I'm just going to quickly correct that, but this is a very common mistake, even on the iPhone, where my name is always automatically corrected to Alex, but I always recommend just quickly going through and checking your subtitles. All we have to do is click on the Options tab right here to download it as an SRT file so we can upload it to YouTube. I'm going to return to YouTube and this time I'm just going to delete the manually entered subtitles. Click Open, and as you can see, YouTube has now imported all of the subtitles with my corrections. I would love to hear your questions in the comment section below if you have any regarding adding subtitles to a YouTube video."
h5 = "And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks.And then we're just gonna select Upload video.Now, there's always been the possibility to add subtitles to a YouTube video, but here YouTube implemented this section directly within the upload process because they know how important subtitles are and how important they're becoming because video content is dominating online.Select our YouTube video, click Open.And as you can see, our YouTube video is now imported into VEED's Video Editor.And basically to automatically generate subtitles for my YouTube video, all I have to do is click on the Subtitle tab in the left toolbar.And as you can see, this process may take a few seconds to a few minutes, depending on the length of your video to automatically transcribe your videos audio into text and turn that text into subtitles.And in this video, I'm gonna be showing you how to add subtitles to any video online.And we're just going to select SRT Format which is the subtitle format, click on Download.And that is how to upload subtitles to a YouTube video after YouTube's new upload process update."
r5 = "Afterwards, I'm going to show you how to automatically create a subtitle SRT file so you can upload your subtitles along with your YouTube video at the same time, in just a few clicks. Initially, we'll be manually adding our subtitles to the YouTube video. Next, we'll just choose Upload video. Although adding subtitles to a YouTube video has always been an option, YouTube decided to integrate this feature right into the upload process because they recognize the value of subtitles and how important they are growing as video content takes over the internet. Click Open after selecting our YouTube video. And as you can see, VEED's Video Editor has now imported our YouTube video. Basically, to create subtitles for my YouTube video automatically, I only need to select the Subtitle tab from the left toolbar. And as you can see, depending on the length of your video, this process may take a few seconds to a few minutes to automatically convert your video's audio into text and create subtitles. And I'll be demonstrating how to add subtitles to any online video in this video. Simply click on Download after selecting SRT Format as the subtitle format. And that's how, following YouTube's recent upload process update, to add subtitles to a video."
h6 = "And in this video, I'm going to be showing you how to add subtitles to a YouTube video.And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks.So once we're on YouTube, to add subtitles to our video while we upload it, we're just going to upload a video as we would normally.Now we're taken to the YouTube video upload page and this is where I'm going to select the YouTube video I want to upload to YouTube.Now, there's always been the possibility to add subtitles to a YouTube video, but here YouTube implemented this section directly within the upload process because they know how important subtitles are and how important they're becoming because video content is dominating online.Now to add the subtitles, all we're going to do is click on Add right next to add subtitles.And that's how you add subtitles to your YouTube video.And basically to automatically generate subtitles for my YouTube video, all I have to do is click on the Subtitle tab in the left toolbar.And in this video, I'm gonna be showing you how to add subtitles to any video online.And that is how to upload subtitles to a YouTube video after YouTube's new upload process update."
r6 = "Additionally, I'll demonstrate how to add subtitles to a YouTube video in this video. Afterwards, I'm going to show you how to automatically create a subtitle SRT file so you can upload your subtitles along with your YouTube video at the same time, in just a few clicks. Initially, we'll be manually adding our subtitles to the YouTube video. So, once we're on YouTube, we'll simply upload a video as we normally would and add subtitles to it as we go. We've now been directed to the YouTube video upload page, where I will choose the YouTube video I want to upload. Although adding subtitles to a YouTube video has always been an option, YouTube decided to integrate this feature right into the upload process because they recognize the value of subtitles and how important they are growing as video content takes over the internet. We simply need to click Add next to add subtitles in order to add the subtitles. And that's the procedure for adding subtitles to your YouTube video. And all I have to do is click the Subtitle tab in the left toolbar to basically automatically create subtitles for my YouTube video. And I'll be demonstrating how to add subtitles to any online video in this video. And that's how, following YouTube's recent upload process update, to add subtitles to a video."
h7 = ""
r7 = ""
h8 = ""
r8 = ""

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)
scores2 = rouge.get_scores(h2, r2)
scores3 = rouge.get_scores(h3, r3)
scores4 = rouge.get_scores(h4, r4)
scores5 = rouge.get_scores(h5, r5)
scores6 = rouge.get_scores(h6, r6)
print(scores)
print(scores2)
print(scores3)
print(scores4)
print(scores5)
print(scores6)
