from rouge import Rouge

hypothesis = "And we'll be adding our subtitles to the YouTube video manually, but after I've shown you this, I'm gonna be showing you how to automatically generate a subtitle SRT file so you can upload your subtitles with your YouTube video at the same time, in just a few clicks. So, once we're on YouTube, we'll simply upload a video as we normally would and add subtitles to it as we go. I then simply choose my YouTube videos after clicking on Select Files. Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. So even YouTube knows that if you add subtitles to video, you're going to get more reach and more views. So I've got this video and I want to add subtitles to it. This is the exact video that we typed out manually within YouTube's studio. And then to download it as an SRT file so we can upload it to YouTube, all we're going to do is click on the Options tab right here. And then I'm just going to select the SRT file that we've just automatically generated using VEED."

reference = "And we'll be manually adding subtitles, but after showing you this, I'm gonna be showing you how generate a subtitle SRT file so you can upload your subtitles with your YouTube video automatically fast. So, once we're on YouTube, we'll simply upload a video as we normally would and add subtitles to it as we go. I then simply choose my YouTube videos after clicking on Select Files. Once we click Next to advance to the following step for the video elements, you'll notice that we now have this new section at the top with Add subtitles immediately below it. So even YouTube knows that if you add subtitles to video, you're going to get more reach and more views. This is the exact video that we typed out manually within YouTube's studio. After we have to download it as an SRT file to upload it to YouTube, the only action we need to take is to click on this Options tab.. And then I'll just choose the SRT file that VEED just used to generate it automatically after that."

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)
print(scores)
