from rouge import Rouge

hypothesis = "snow leopard, which was two miles away. First day. And we got the snow leopards. first few days of the shoot. And, you know, it's been five days now not to shave until I see a snow leopard, which could prove to be a mistake because We are getting slightly desperate here. I've spent the last month trying to film a rock-coloured cat amongst a mountain And surprisingly enough, so fa r, I've been unsuccessful About to see my first ever snow leopard, There's a snow leopard on a carcass. and try and grab little bits of the carcass."

reference = "Two miles away was the snow leopard on initial day. The first few days of the filming, we also encountered the snow leopards. And, you know, I haven't shaved in five days. This may turn out to be a mistake because we are starting to become a little desperate. The past month has been spent trying to capture on camera a cat with a rock-coloured coat. Surprisingly, I haven't been successful thus far. I'm about to see a snow leopard for the first time; it's perched on a cadaver. and make an effort to seize scraps of the carcass."
h2 = "The leopard was being persecuted by these magpies that would, that would sort of hop around it, and they'd sort of creep up and creep up and try and grab little bits of the carcass. I think I'm going to make a vow not to shave until I see a snow leopard, which could prove to be a mistake because we've still got another month here. And then every now and again, the leopard would jump out with all its fury and try and grab one or at least scare them away. And surprisingly enough, so far, I've been unsuccessful About to see my first ever snow leopard, apparently if I look through here. There's a snow leopard on a carcass. But the leopard has to continually protect its prey during the daytime or else it will be destroyed. So we've just met the scientists who are based here, and they've been here for three months and they've seen one snow leopard, which was two miles away. I've spent the last month trying to film a rock-coloured cat amongst a mountain range of cat-coloured rocks."
r2 = "These magpies were hunting the leopard; they would sort of hop around it, then sort of creep up and creep up, trying to snag scraps of the carcass. It might be a mistake given that we still have another month here, but I think I'm going to swear off shaving until I see a snow leopard. The leopard would occasionally charge out in an attempt to seize one or at the very least chase it away. And surprisingly, I've had no luck thus far. However, if I look through here, it appears that I will soon see my first snow leopard. A snow leopard is perched on a carcass. However, the leopard must constantly defend its prey during the day in order to keep it alive. So far in their three months here, the scientists we've just met have only seen one snow leopard, and that one was two miles away. The past month has been spent trying to capture a rock-colored cat in a mountain range of rock-colored cats."
h3 = "The leopard was being persecuted by these magpies that would, that would sort of hop around it, and they'd sort of creep up and creep up and try and grab little bits of the carcass. I think I'm going to make a vow not to shave until I see a snow leopard, which could prove to be a mistake because we've still got another month here. And then every now and again, the leopard would jump out with all its fury and try and grab one or at least scare them away. There's a snow leopard on a carcass. And surprisingly enough, so far, I've been unsuccessful About to see my first ever snow leopard, apparently if I look through here. But the leopard has to continually protect its prey during the daytime or else it will be destroyed. And we got the snow leopards. I've spent the last month trying to film a rock-coloured cat amongst a mountain range of cat-coloured rocks."
r3 = "These magpies were hunting the leopard; they would sort of hop around it, then sort of creep up and creep up, trying to snag scraps of the carcass. It might be a mistake given that we still have another month here, but I think I'm going to swear off shaving until I see a snow leopard. The leopard would occasionally charge out in an attempt to seize one or at the very least chase it away. A snow leopard is perched on a carcass. And surprisingly, I've had no luck thus far. However, if I look through here, it appears that I will soon see my first snow leopard. However, the leopard must constantly defend its prey during the day in order to keep it alive. We also have snow leopards. The past month has been spent trying to capture a rock-coloured cat in a mountain range of rock-coloured cats."
h4 = "So we've just met the scientists who are based here, and they've been here for three months and they've seen one snow leopard, which was two miles away. I think I'm going to make a vow not to shave until I see a snow leopard, which could prove to be a mistake because we've still got another month here. I've spent the last month trying to film a rock-coloured cat amongst a mountain range of cat-coloured rocks. And surprisingly enough, so far, I've been unsuccessful About to see my first ever snow leopard, apparently if I look through here. But the leopard has to continually protect its prey during the daytime or else it will be destroyed. Once the vultures come down, they they just demolish a huge carcass in a very short space of time. The leopard was being persecuted by these magpies that would, that would sort of hop around it, and they'd sort of creep up and creep up and try and grab little bits of the carcass. And then every now and again, the leopard would jump out with all its fury and try and grab one or at least scare them away. "
r4 = "So far in their three months here, the scientists we've just met have only seen one snow leopard, and that one was two miles away. It might be a mistake given that we still have another month here, but I think I'm going to swear off shaving until I see a snow leopard. The past month has been spent trying to capture a rock-colored cat in a mountain range of rock-colored cats. And surprisingly, I've had no luck thus far. However, if I look through here, it appears that I will soon see my first snow leopard. However, the leopard must constantly defend its prey during the day in order to keep it alive. The moment the vultures descend, they quickly and completely consume a huge carcass. These magpies were hunting the leopard; they would sort of hop around it, then sort of creep up and creep up, trying to snag scraps of the carcass. The leopard would occasionally charge out in an attempt to seize one or at the very least chase it away."
h5 = "So we've just met the scientists who are based here, and they've been here for three months and they've seen one snow leopard, which was two miles away. And we got the snow leopards. Now we're into the reality of snow leopards. I think I'm going to make a vow not to shave until I see a snow leopard, which could prove to be a mistake because we've still got another month here. And surprisingly enough, so fa r, I've been unsuccessful About to see my first ever snow leopard, apparently if I look through here. There's a snow leopard on a carcass. I can shave, I can shave now. The leopard was being persecuted by these magpies that would, that would sort of hop around it, and they'd sort of creep up and creep up and try and grab little bits of the carcass."
r5 = "So far in their three months here, the scientists we've just met have only seen one snow leopard, and that one was two miles away. We also have snow leopards. We are now dealing with snow leopard reality. It might be a mistake given that we still have another month here, but I think I'm going to swear off shaving until I see a snow leopard. And surprisingly, I haven't been successful thus far. If I look through here, I might be about to see my first ever snow leopard. A snow leopard is perched on a carcass. I am now capable of shaving. These magpies were hunting the leopard; they would sort of hop around it, then sort of creep up and creep up, trying to snag scraps of the carcass."
h6 = "So we've just met the scientists who are based here, and they've been here for three months and they've seen one snow leopard, which was two miles away. And we got the snow leopards. Now we're into the reality of snow leopards. I think I'm going to make a vow not to shave until I see a snow leopard, which could prove to be a mistake because we've still got another month here. And surprisingly enough, so fa r, I've been unsuccessful About to see my first ever snow leopard, apparently if I look through here. There's a snow leopard on a carcass. I can shave, I can shave now. The leopard was being persecuted by these magpies that would, that would sort of hop around it, and they'd sort of creep up and creep up and try and grab little bits of the carcass."
r6 = "So far in their three months here, the scientists we've just met have only seen one snow leopard, and that one was two miles away. We also have snow leopards. We are now dealing with snow leopard reality. It might be a mistake given that we still have another month here, but I think I'm going to swear off shaving until I see a snow leopard. And surprisingly, I haven't been successful thus far. If I look through here, I might be about to see my first ever snow leopard. A snow leopard is perched on a carcass. I am now capable of shaving. These magpies were hunting the leopard; they would sort of hop around it, then sort of creep up and creep up, trying to snag scraps of the carcass."

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)
scores2 = rouge.get_scores(h2, r2)
scores3 = rouge.get_scores(h3, r3)
scores4 = rouge.get_scores(h4, r4)
scores5 = rouge.get_scores(h5, r5)
scores6 = rouge.get_scores(h6, r6)
print(scores)
print(scores2)
print(scores3)
print(scores4)
print(scores5)
print(scores6)
